language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
notifications:
  irc: irc.freenode.org#simplesconsultoria
