language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=4.3 DEXTERITY_ONLY=true
matrix:
  fast_finish: true
install:
- python bootstrap.py --setuptools-version=20.9.0
- bin/buildout annotate
- bin/buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#simplesconsultoria
